"""Shared paths and file loaders for the Job Applier.

No LLM SDK lives here anymore: Claude Code is the reasoning layer and drives
everything through the MCP tools. These helpers just locate and load the
local materials (profile, resume, history, context knowledge base).

Per-user paths are resolved lazily through src/profiles.py (the active
profile). Attribute access like ``config.HISTORY_PATH`` still works — a
module-level ``__getattr__`` maps the old constant names onto the active
profile — so call sites did not have to change when the profile system landed.
Shared, user-neutral assets (watchlist, postings store, location aliases,
discovery config) remain true module constants at the repo root.
"""

import json
import os
import tempfile
import yaml
from pathlib import Path

from . import profiles

# Shared (user-neutral) paths — real constants.
BASE_DIR = profiles.REPO_DIR
DATA_DIR = BASE_DIR / "data"                    # shared store + refresh outputs
DATA_DIR.mkdir(exist_ok=True)

WATCHLIST_PATH = BASE_DIR / "watchlist.yaml"
LOCATION_ALIASES_PATH = BASE_DIR / "location_aliases.yaml"  # curated alias map for location normalization
POSTINGS_DB_PATH = DATA_DIR / "postings.db"     # local postings store (cache of public data)
DIGEST_PATH = DATA_DIR / "digest-latest.md"     # regenerated by every refresh run
DISCOVERY_PATH = BASE_DIR / "discovery.yaml"    # startup-discovery source config
DISCOVERY_REPORT_PATH = DATA_DIR / "discovery-latest.md"  # regenerated by every discover run

# Per-profile paths, resolved lazily so profile switching (env var, tests,
# applyer.local.json) needs no reimport. Old constant names preserved.
_PROFILE_ATTRS = {
    "USER_PROFILE_PATH": lambda p: p.profile_yaml,
    "EEO_PATH": lambda p: p.eeo_yaml,
    "JOB_CRITERIA_PATH": lambda p: p.criteria_yaml,
    "CONTEXT_DIR": lambda p: p.context_dir,
    "HISTORY_PATH": lambda p: p.history_json,
    "APPLICATIONS_PATH": lambda p: p.applications_json,
    "PREP_DIR": lambda p: p.prep_dir,
    "RESUMES_DIR": lambda p: p.resumes_dir,
    "RESUME_TEXT_PATH": lambda p: p.resume_txt,
    "RUNTIME_DIR": lambda p: p.runtime_dir,
    "BROWSER_PROFILE_DIR": lambda p: p.browser_dir,
}


def __getattr__(name: str):
    fn = _PROFILE_ATTRS.get(name)
    if fn is None:
        raise AttributeError(f"module 'src.config' has no attribute '{name}'")
    return fn(profiles.active())


def active_profile() -> profiles.ActiveProfile:
    return profiles.active()


_RESUME_UPLOAD_CANDIDATES = ["resume.pdf", "resume.docx", "resume.doc", "resume.txt"]


def resume_upload_path() -> Path:
    """Path of the DEFAULT resume file to upload to forms (PDF/DOCX preferred).
    Per-job tailored resumes are resolved separately (see src/tailor.py); this is
    the fallback when no tailored artifact exists for the job."""
    root = profiles.active().root
    for name in _RESUME_UPLOAD_CANDIDATES:
        p = root / name
        if p.exists():
            return p
    return profiles.active().resume_txt


def base_resume_docx() -> Path | None:
    """The user-provided `resume.docx` base template that per-job tailoring edits
    in place (JOB-6). Returns None if the user hasn't added one yet — callers
    fall back to the default upload (`resume_upload_path`)."""
    p = profiles.active().resume_docx
    return p if p.exists() else None


def extract_pdf_text(path) -> str:
    """Extract text from a PDF (empty string if pypdf is missing or it fails)."""
    try:
        from pypdf import PdfReader
    except ImportError:
        return ""
    try:
        reader = PdfReader(str(path))
        return "\n".join((page.extract_text() or "") for page in reader.pages)
    except Exception:
        return ""


def load_user_profile() -> dict:
    """The profile facts, with local-only EEO entries (eeo.yaml) merged in.

    EEO values keep their {value, eeo: true} wrapper shape whether they come
    from a legacy inline profile or the split eeo.yaml, so downstream handling
    (voluntary self-ID only, never persisted) is unchanged. eeo.yaml never
    leaves this machine — the merge happens here, below any API boundary."""
    prof = profiles.active()
    if not prof.profile_yaml.exists():
        raise FileNotFoundError(f"User profile not found at {prof.profile_yaml}")
    with open(prof.profile_yaml, "r", encoding="utf-8") as f:
        data = yaml.safe_load(f) or {}
    if prof.eeo_yaml.exists():
        with open(prof.eeo_yaml, "r", encoding="utf-8") as f:
            eeo = yaml.safe_load(f) or {}
        for key, value in eeo.items():
            if not isinstance(value, dict):
                value = {"value": value, "eeo": True}
            value.setdefault("eeo", True)
            data[key] = value
    return data


def sync_resume_text_from_pdf() -> bool:
    """If a resume.pdf exists and is newer than resume.txt, extract its text and
    (over)write resume.txt so the reasoning text stays in sync with the document
    that is actually uploaded. Returns True if the sync happened. No-op when
    there is no PDF, it yields no extractable text, or resume.txt is already
    current — leaving a hand-written resume.txt untouched."""
    prof = profiles.active()
    pdf = prof.resume_pdf
    if not pdf.exists():
        return False
    txt = prof.resume_txt
    if txt.exists() and txt.stat().st_mtime >= pdf.stat().st_mtime:
        return False
    text = extract_pdf_text(pdf)
    if not text.strip():
        return False
    txt.write_text(text, encoding="utf-8")
    return True


def load_watchlist() -> list:
    """Return the list of watchlist companies ({name, ats, slug})."""
    if not WATCHLIST_PATH.exists():
        return []
    with open(WATCHLIST_PATH, "r", encoding="utf-8") as f:
        data = yaml.safe_load(f) or {}
    return data.get("companies", [])


def load_discovery_config() -> dict:
    """Load discovery.yaml (startup-discovery sources for python -m src.discover)."""
    if not DISCOVERY_PATH.exists():
        return {}
    with open(DISCOVERY_PATH, "r", encoding="utf-8") as f:
        return yaml.safe_load(f) or {}


def load_location_aliases() -> dict:
    """Load location_aliases.yaml → {lowercased alias: canonical}. The curated
    half of location normalization; regex canonicalization handles the rest."""
    if not LOCATION_ALIASES_PATH.exists():
        return {}
    with open(LOCATION_ALIASES_PATH, "r", encoding="utf-8") as f:
        data = yaml.safe_load(f) or {}
    return {str(k).lower(): str(v) for k, v in (data.get("aliases") or {}).items()}


def load_foreign_scope() -> dict:
    """Load the `foreign_scope` block of location_aliases.yaml →
    {"metros": {country: [lowercased metro, ...]}}. The curated metro
    vocabulary behind the remote-scope check (JOB-123); keyed by country so
    allowing a country also stops its metros counting as foreign. Additive to
    the alias map above, which it deliberately leaves alone."""
    if not LOCATION_ALIASES_PATH.exists():
        return {"metros": {}}
    with open(LOCATION_ALIASES_PATH, "r", encoding="utf-8") as f:
        data = yaml.safe_load(f) or {}
    scope = data.get("foreign_scope") or {}
    return {"metros": {str(country): [str(m).lower() for m in (metros or [])]
                       for country, metros in (scope.get("metros") or {}).items()}}


def load_search_criteria() -> dict:
    """Load the profile's criteria.yaml (search defaults + the strict baseline bar)."""
    path = profiles.active().criteria_yaml
    if not path.exists():
        return {}
    with open(path, "r", encoding="utf-8") as f:
        return yaml.safe_load(f) or {}


def load_resume() -> str:
    """Return the resume as text for reasoning: resume.txt if present, else
    text extracted from resume.pdf."""
    prof = profiles.active()
    if prof.resume_txt.exists():
        return prof.resume_txt.read_text(encoding="utf-8")
    if prof.resume_pdf.exists():
        text = extract_pdf_text(prof.resume_pdf)
        if text.strip():
            return text
    raise FileNotFoundError(
        f"No resume found. Add resume.txt or resume.pdf in {prof.root}"
    )


def _atomic_write_json(path: Path, payload) -> None:
    """Whole-file JSON write via temp + os.replace so a concurrent reader never
    sees a truncated file and a crash never loses the previous version."""
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(dir=str(path.parent), suffix=".tmp")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            json.dump(payload, f, indent=2, ensure_ascii=False)
        os.replace(tmp, path)
    except BaseException:
        try:
            os.unlink(tmp)
        except OSError:
            pass
        raise


def load_history() -> list:
    path = profiles.active().history_json
    if path.exists():
        with open(path, "r", encoding="utf-8") as f:
            try:
                return json.load(f)
            except json.JSONDecodeError:
                return []
    return []


def save_history(history: list) -> None:
    _atomic_write_json(profiles.active().history_json, history)


def load_applications() -> list:
    """The application log: one record per submitted application."""
    path = profiles.active().applications_json
    if path.exists():
        with open(path, "r", encoding="utf-8") as f:
            try:
                return json.load(f)
            except json.JSONDecodeError:
                return []
    return []


def save_applications(applications: list) -> None:
    _atomic_write_json(profiles.active().applications_json, applications)
